config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  # deviseの設定。deviseではなくuserコントローラから実装しているため、パスを直接指定する
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }
  devise_for :admins,controllers: {
    sessions: 'admins/sessions'
  }
 
  resources :users,only:[:index,:show,:edit,:update] do
    member do
      get :following
      get :followers
      get :favorites
    end
  end

  resources :relationships, only: [:create,:destroy]

  resources :study_logs,only: [:show,:new,:create,:edit,:update,:destroy] do
    resources :study_log_comments, only: [:create,:destroy]
    resource :study_log_favorites, only: [:create,:destroy]
    collection do
      get :modal_study_log_new
    end
  end

  resources :notes,only: [:show,:new,:create,:edit,:update,:destroy] do
    resources :note_comments, only: [:create,:destroy]
    resource :note_favorites, only: [:create,:destroy]
    collection do
      get :preview
     end
  end

  resources :searchs,only: [:index] do
    collection do
      get :sort
      get :search
      get :more
    end
  end

  resources :timelines,only: [:index]
  resources :rooms,only:[:index,:show,:create] do
    collection do
      get :search
      get :return
      get :more
    end
  end

  resources :notifications, only: [:index]

  namespace :admins do
    resources :users, only: [:index,:show,:destroy,:update]
    resources :study_logs, only: [:index,:show,:destroy]
    resources :notes, only: [:index,:show,:destroy]
    resources :tags,only: [:index,:edit,:update]
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :note_favorites, dependent: :destroy
  has_many :note_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # acts_as_taggable_onを利用するため定義
  acts_as_taggable

  validates :title, presence: true
  validates :body, presence: true
  validate :invalid_note_tag
  validate :invalid_note_tag_size

  def favorited_by?(user)
    note_favorites.where(user_id: user.id).exists?
  end

  # tag_listはgemで行っているため、バリデーションを作成する必要があった
  # 以下でタグが存在しているかチェックを行う(default:0)
  @taglist_count = 0

  def set_taglist_exist(tag_list)
    @taglist_count = tag_list
  end

  def invalid_note_tag
    return unless @taglist_chk

    errors[:base] << 'タグが入力されていません'
  end

  def invalid_note_tag_size
    return unless @taglist_count > 6

    errors[:base] << 'タグは6つまで登録できます'
  end

end

app/controllers/admins/notes_controller.rb
class Admins::NotesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @notes = Note.includes(%i[user tags])
                 .page(params[:page])
                 .per(6)
  end

  def show
    @note = Note.find(params[:id])
    @note_comments = @note.note_comments
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    flash[:info] = 'ノートを削除しました'
    redirect_to admins_notes_path
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  before_action :correct_user, only: %i[edit]

  def new
    @note = current_user.notes.new
  end

  def create
    @note = current_user.notes.new(note_params)
    @note.set_taglist_exist(params[:note][:tag_list].split(',').size)
    if @note.save
      # 以下はランダムなカラーコードを作成するメソッドを呼び出している
      create_tag_color
      flash[:success] = 'ノートを投稿しました。'
      redirect_to note_path(@note)
    else
      render 'new'
    end
  end

  def show
    @note = Note.find(params[:id])
    @note_comments = @note.note_comments.all
    @note_comment = @note.note_comments.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    @note.set_taglist_exist(params[:note][:tag_list].split(',').size)

    if @note.update(note_params)
      flash[:success] = 'ノートを更新しました'
      redirect_to note_path(@note)
      # 以下はランダムなカラーコードを作成するメソッドを呼び出している
      create_tag_color
    else
      render 'edit'
    end
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    flash[:warning] = '投稿を削除しました。'
    redirect_to timelines_path
  end

  # 以下APIの処理
  def preview
    @body = view_context.markdown(params[:body])
    respond_to do |format|
      format.json
    end
  end

  private

  def note_params
    params.require(:note).permit(:user_id, :title, :body, :tag_list)
  end

  def correct_user
    @note = Note.find(params[:id])
    redirect_to root_path unless current_user.id == @note.user_id
  end
end

app/helpers/admins/notes_helper.rb
module Admins::NotesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note_distribution.html.erb
<% if request.referer&.include?("/searchs") %>
    <%= link_to "戻る", searchs_path(genre_id: 2)  %>
<% elsif request.referer&.include?("/users") %>
    <%= link_to "戻る",user_path(note.user, tab_code: 2) %>
<% else %>
    <%= link_to "戻る",timelines_path(tab_code: 2) %>
<% end %>

app/views/notes/_note_form.html.erb
<%= form_with model:[note ,note_comment],remote: true,class:"w-100" do |f| %>
  <%= f.text_area :comment, rows:'5', class: "form-control w-100",placeholder: "コメントを入力してください" %>
  <%= f.submit "コメントする", class: "btn btn-primary mt-2" %>
<% end %>

app/views/notes/_note_list.html.erb
<% if notes.empty? %>
  <h6 class="ml-3">ノートが投稿されていません。</h6>  
<% else %>
  <% notes.each do |note| %>
    <div class="note-card mt-2">
      <div class="card-body">
        <div class="d-flex">
          <%= link_to user_path(note.user) do %>
            <%= attachment_image_tag note.user, :profile_image, :fill, 100, 100, class: "pull-left list-img profile-img", fallback: "no_image.png",size: "100x100" %>
          <% end %>
          <div class="d-flex align-items-center">
            <div class="margin-left">
              <div class="link-position  mb-3 mt-2">
                <%= link_to note_path(note) do %>
                  <div class="title"><%= note.title %></div>
                <% end %>
              </div>
              <h6 class="text-muted"><%= note.created_at.strftime("%Y年%m月%d日") %><br>
                <%= note.user.name %>
              </h6>
            </div>
            <div class="value">
              <i class="far fa-thumbs-up"> <%= note.note_favorites.count %></i>
              <i class="far fa-comment"> <%= note.note_comments.count %></i>        
            </div>
            <div class="badge-position">
              <% note.tags.pluck(:name).each do |tag| %>
                <%= link_to tag,searchs_path(tag_name:tag,search_id:1,genre_id: 2),class: "badge-success p-1 badge-tag tag_list" ,data: {"turbolinks" => false} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/notes/edit.html.erb
<div class="container">
  <div class="d-flex justify-content-end">
      <%= link_to "戻る", note_path(@note) %>
  </div>
  <div class="row">
    <h3>ノート編集</h3>
  </div>
  <div class="row">
    <div class="col-12">
      <%= form_with model: @note,local: true do |f| %>
        <%= render 'layouts/error_messages', model: @note %>
        <h6>タイトル</h6>
        <%= f.text_field :title, class: "form-control mb-2" %>
        <h6>タグ</h6>
        <%= f.text_field :tag_list,value: @note.tag_list.join(','),"data-role" => "tagsinput", class: "form-control mb-2" %>
        <div class="d-flex mb-3">
          <div class="note-area">
            <h6>本文</h6>
            <!-- プレビュー用のタグ -->
            <div id="preview-area"></div>
            <div class="input-field">
              <%= f.text_area :body, class: "form-control",style: "height: 60vh;" ,id: "md-textarea"%>     
            </div>
          </div>
        </div>
        <button type="button" id="markdown" class="btn btn-info" disabled>
          記述する
        </button>
        <button type="button" id="preview" class="btn btn-info mr-5">
          プレビューする      
        </button>
        <%= f.submit "投稿する",class: "btn btn-success" %>
          <div class="row col-12 mt-3">
            <%= link_to "ノートを削除する",note_path(@note),method: :delete, data: { confirm: "本当に削除しますか？",cancel: "やめる", commit: "削除する"},title: '投稿の削除',class: "btn btn-danger"%>
          </div>
      <% end %>   
    </div>
  </div>  
</div>

app/views/notes/new.html.erb
<div class="container">
  <div class="d-flex justify-content-end">
    <%= link_to "戻る", timelines_path %>
  </div>
  <div class="row">
    <h3>ノートを書く</h3>
  </div>
  <div class="row">
    <div class="col-12">
      <%= form_with model: @note,local:true do |f| %>
        <%= render 'layouts/error_messages', model: @note %>
        <h6>タイトル</h6>
        <%= f.text_field :title, class: "form-control mb-2", placeholder: "タイトルを入力してください" %>
        <h6>タグ</h6>
        <%= f.text_field :tag_list,value: @note.tag_list.join(','),"data-role" => "tagsinput", id: "add_note_tags", class: "form-control mb-2 w-100", placeholder: "「,」区切りで追加してください"%>
        <div class="d-flex mb-3">
          <div class="w-100">
            <h6>本文</h6>
            <!-- プレビュー用のタグ -->
            <div id="preview-area" class="col-12">
            </div>
            <div class="input-field">
              <%= f.text_area :body, class: "form-control",id: "md-textarea", placeholder: "マークダウン記法が使えます"%>
            </div>
          </div>
        </div>
        <button id="markdown" type="button" class="btn btn-info" disabled>
          記述する
        </button>
        <button type="button" id="preview" class="btn btn-info mr-5">
          プレビューする
        </button>
          <%= f.submit "投稿する",class: "btn btn-success mt-2" %>
      <% end %>   
    </div>
  </div>  
</div>

<!-- render先で画面リロードを行うとroutingエラーが発生するため、明示的にパスを指定してリダイレクトさせる -->
<% if @note.errors.present? %>
<script type="text/javascript">
  $(document).ready(function() {
  history.pushState('', '', location.href + '/new')
  });
</script>
<% end %>

app/views/notes/show.html.erb
<div class="container">
  <div class="d-flex justify-content-end">
    <!-- new・editから来ていたらtimelines、searchsから来ていたらsearch、showから来ていたらuser -->
    <%= render 'note_distribution',note: @note %>
  </div>
  <div class="row">
    <h3>ノート</h3>
  </div>
  <div class="row">    
    <div class="note-card col-12">
      <div class="link">
        <% if user_signed_in? && current_user.id == @note.user.id %>
          <%= link_to "編集する",edit_note_path(@note),data: {"turbolinks" => false} %>
        <% end %>
        <div class="d-flex justify-content-end" id="note-favorite-<%= @note.id %>" >
          <%= render 'note_favorites/note_favorite', note: @note%>
        </div>
      </div>
      <div class="row card-body">
      <div class="col-6 mb-2 font-size">タイトル</div>
        <div class="col-12 font-size">
          <%= @note.title %>
        </div>
      </div>
      <hr class="note-under">
      <div class="row card-body">
        <div class="col-12  mb-2 font-size">
          タグ
        </div>
        <div class="col-12">
          <% @note.tag_list.each do |tag| %> 
            <%= link_to tag,searchs_path(tag_name:tag,search_id:1,genre_id: 2),class: "badge badge-success p-1 badge-tag",data: {"turbolinks" => false} %>
          <% end %>                    
        </div>
      </div>
      <hr class="note-under">
      <div class="row card-body">
        <div class="col-12 mb-5">
          <div class="ml-3">
            <%= markdown(@note.body) %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <h4 class="mt-4">コメント</h4>
  <div class="row" id="note-comments">
    <%= render 'note_comments/note_comments',note: @note,note_comments: @note_comments %>
  </div>
  <div class="row"> 
    <%= render 'notes/note_form',note: @note,note_comment: @note_comment %>    
  </div>
</div>