config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  # deviseの設定。deviseではなくuserコントローラから実装しているため、パスを直接指定する
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }
  devise_for :admins,controllers: {
    sessions: 'admins/sessions'
  }
 
  resources :users,only:[:index,:show,:edit,:update] do
    member do
      get :following
      get :followers
      get :favorites
    end
  end

  resources :relationships, only: [:create,:destroy]

  resources :study_logs,only: [:show,:new,:create,:edit,:update,:destroy] do
    resources :study_log_comments, only: [:create,:destroy]
    resource :study_log_favorites, only: [:create,:destroy]
    collection do
      get :modal_study_log_new
    end
  end

  resources :notes,only: [:show,:new,:create,:edit,:update,:destroy] do
    resources :note_comments, only: [:create,:destroy]
    resource :note_favorites, only: [:create,:destroy]
    collection do
      get :preview
     end
  end

  resources :searchs,only: [:index] do
    collection do
      get :sort
      get :search
      get :more
    end
  end

  resources :timelines,only: [:index]
  resources :rooms,only:[:index,:show,:create] do
    collection do
      get :search
      get :return
      get :more
    end
  end

  resources :notifications, only: [:index]

  namespace :admins do
    resources :users, only: [:index,:show,:destroy,:update]
    resources :study_logs, only: [:index,:show,:destroy]
    resources :notes, only: [:index,:show,:destroy]
    resources :tags,only: [:index,:edit,:update]
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  belongs_to :visit, class_name: 'User', foreign_key: 'visit_id'
  # 以下は外部キーがnullの可能性があるのでoptional: trueを指定
  belongs_to :study_log, optional: true
  belongs_to :study_log_comment, optional: true
  belongs_to :note, optional: true
  belongs_to :note_comment, optional: true

  validates :user_id, presence: true
  validates :user_id, presence: true
  validates :action, presence: true
  validates :checked, inclusion: { in: [true, false] }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.passive_notifications
                                 .where.not(user_id: current_user.id)
    # 自身の投稿については既にchecked:trueとなっているため考慮しない
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <h3>通知</h3>
  </div>
    <% if @notifications.exists? %>
      <% @notifications.each do |notification| %>
        <div class="row">
          <div class="col-12">
            <div>            
              <%= link_to user_path(notification.user) do%>
                <%= attachment_image_tag notification.user, :profile_image, :fill, 50, 50,  class: "pull-left profile-img", fallback: "no_image.png",size: "50x50" %>
                <%= notification.user.name %>
              <% end %>さんが
              <% case notification.action %>
              <% when 'follow'%>
                あなたをフォローしました
                <hr>
              <% when 'study_log_favorite' %>
                <b><%= link_to '積み上げ', study_log_path(notification.study_log_id) %></b>にいいねしました。
                <hr>            
              <% when 'note_favorite' %>
                <b><%= link_to 'ノート', note_path(notification.note_id) %></b>にいいねしました。
                <hr>      
              <% when 'study_log_comment' %>
                <b><%= link_to '積み上げ', study_log_path(notification.study_log_id) %></b>にコメントしました。<br>
                <span class="ml-5 text-muted"><%= StudyLogComment.find_by(id: notification.study_log_comment_id).comment %> </span>
                <hr>
              <% when 'note_comment' %>
                <b><%= link_to 'ノート', note_path(notification.note_id) %></b>にコメントしました。<br>
                <span class="ml-5 text-muted"><%= NoteComment.find_by(id: notification.note_comment_id).comment %></span>
                <hr>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
    通知はありません
  <% end %>
</div>