config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  # deviseの設定。deviseではなくuserコントローラから実装しているため、パスを直接指定する
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }
  devise_for :admins,controllers: {
    sessions: 'admins/sessions'
  }
 
  resources :users,only:[:index,:show,:edit,:update] do
    member do
      get :following
      get :followers
      get :favorites
    end
  end

  resources :relationships, only: [:create,:destroy]

  resources :study_logs,only: [:show,:new,:create,:edit,:update,:destroy] do
    resources :study_log_comments, only: [:create,:destroy]
    resource :study_log_favorites, only: [:create,:destroy]
    collection do
      get :modal_study_log_new
    end
  end

  resources :notes,only: [:show,:new,:create,:edit,:update,:destroy] do
    resources :note_comments, only: [:create,:destroy]
    resource :note_favorites, only: [:create,:destroy]
    collection do
      get :preview
     end
  end

  resources :searchs,only: [:index] do
    collection do
      get :sort
      get :search
      get :more
    end
  end

  resources :timelines,only: [:index]
  resources :rooms,only:[:index,:show,:create] do
    collection do
      get :search
      get :return
      get :more
    end
  end

  resources :notifications, only: [:index]

  namespace :admins do
    resources :users, only: [:index,:show,:destroy,:update]
    resources :study_logs, only: [:index,:show,:destroy]
    resources :notes, only: [:index,:show,:destroy]
    resources :tags,only: [:index,:edit,:update]
  end
end

app/models/study_log.rb
class StudyLog < ApplicationRecord
  belongs_to :user
  has_many :study_log_favorites, dependent: :destroy
  has_many :study_log_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  acts_as_taggable

  validates :working_date, presence: true
  validates :user_id, presence: true
  validates :hour, presence: true
  validates :minute, presence: true
  validates :memo, length: { maximum: 50 }
  validate :invalid_working_date
  validate :invalid_study_tag
  validate :invalid_study_hours
  validate :invalid_study_tag_size

  # 既にいいね ボタンを押しているか確認
  def favorited_by?(user)
    study_log_favorites.where(user_id: user.id).exists?
  end

  # タグの存在確認
  # タグが存在しているかチェックするインスタンス変数を定義(default:false)
  @taglist_count = 0
  # 画面から受け取ったパラメータのtag_listが存在しなければtaglist_chkをtrueに変更する
  def set_taglist_exist(tag_list)
    @taglist_count = tag_list
  end

  # 学習内容のタグが存在しているかバリデーションを行うメソッド
  def invalid_study_tag
    return unless @taglist_count.zero?

    errors[:base] << '学習内容が入力されていません'
  end

  def invalid_study_tag_size
    return unless @taglist_count > 6

    errors[:base] << '学習内容は6つまで登録できます'
  end


  private

  # 未来日の登録を防ぐバリデーション
  def invalid_working_date
    return unless working_date.present? && working_date > Date.today

    errors[:base] << '未来日は入力できません'
  end

  # 学習時間が0を防ぐバリデーション
  def invalid_study_hours
    return unless hour.zero? && minute.zero?

    errors[:base] << '学習時間を入力してください'
  end
end

app/controllers/admins/study_logs_controller.rb
class Admins::StudyLogsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @study_logs = StudyLog.includes(%i[user tags])
                          .page(params[:page])
                          .per(6)
  end

  def show
    @study_log = StudyLog.find(params[:id])
    @study_log_comments = @study_log.study_log_comments.all
  end

  def destroy
    @study_log = StudyLog.find(params[:id])
    # binding.pry
    @study_log.destroy
    redirect_to admins_study_logs_path
    flash[:info] = '学習記録を削除しました'
  end
end

app/controllers/study_logs_controller.rb
class StudyLogsController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  before_action :correct_user, only: %i[edit]

  def show
    @study_log = StudyLog.find(params[:id])
    @study_log_comments = @study_log.study_log_comments.all
    @study_log_comment = @study_log.study_log_comments.new
  end

  def new
    @study_log = current_user.study_logs.new
  end

  def create
    @study_log = current_user.study_logs.new(study_log_params)
    @study_log.set_taglist_exist(params[:study_log][:tag_list].split(',').size)
    if @study_log.save
      # 以下はランダムなカラーコードを作成するメソッドを呼び出している
      create_tag_color
      flash[:success] = '登録が完了しました。この調子で頑張りましょう'
      redirect_to study_log_path(@study_log)
    else
      render 'new'
    end
  end

  def edit
    @study_log = StudyLog.find(params[:id])
  end

  def update
    @study_log = StudyLog.find(params[:id])
    @study_log.set_taglist_exist(params[:study_log][:tag_list].split(',').size)
    if @study_log.update(study_log_params)
      flash[:success] = '更新が完了しました。'
      redirect_to study_log_path(@study_log)
      # 以下はランダムなカラーコードを作成するメソッドを呼び出している
      create_tag_color
    else
      render 'edit'
    end
  end

  def destroy
    study_log = StudyLog.find(params[:id])
    study_log.destroy
    flash[:notice] = '投稿を削除しました。'
    redirect_to timelines_path
  end

  private

  def study_log_params
    params.require(:study_log).permit(:working_date, :memo, :hour, :minute, :tag_list)
  end

  def correct_user
    @study_log = StudyLog.find(params[:id])
    redirect_to root_path unless current_user.id == @study_log.user_id
  end
end

app/helpers/admins/study_logs_helper.rb
module Admins::StudyLogsHelper
end

app/helpers/study_logs_helper.rb
module StudyLogsHelper
end

app/views/study_logs/_study_log_distribution.html.erb
<% if request.referer&.include?("/searchs") %>
    <%= link_to "戻る", searchs_path(genre_id: 1), class: "study-log-back" %>
<% elsif request.referer&.include?("/users") %>
    <%= link_to "戻る",user_path(study_log.user,tab_code: 1), class: "study-log-back" %>
<% else %>
    <%= link_to "戻る",timelines_path(tab_code: 1), class: "study-log-back" %>
<% end %>

app/views/study_logs/_study_log_form.html.erb
<%= form_with model:[study_log ,study_log_comment],remote: true do |f| %>
  <%= f.text_area :comment, rows:'5', class: "form-control mt-2",placeholder: "コメントを入力してください" %>
  <%= f.submit "コメントする", class: "btn btn-primary mt-2" %>
<% end %>

app/views/study_logs/_study_log_list.html.erb
<% if study_logs.empty? %>
  <h6 class="ml-4">学習記録が投稿されていません。</h6>  
<% else %>
  <!-- 表示される学習記録一覧 -->
  <% study_logs.each do |study_log| %>
    <div class="col-xl-4 col-lg-6 col-md-12 mb-2">
      <div class="s-card h-100 study-log-list">
        <div class="s-header d-flex">
          <%= link_to user_path(study_log.user) do %>
            <%= attachment_image_tag study_log.user, :profile_image, :fill, 80, 80,  class: "pull-left profile-img", fallback: "no_image.png",size: "80x80" %>              
          <% end %>
          <div class="ml-3 d-flex flex-column justify-content-center">
            <h6><%= study_log.working_date.strftime("%Y年%m月%d日")%></h6>
            <h5><%= study_log.user.name %></h5>
          </div>
        </div>
        <ul class="list-group">
          <!-- 登録された学習内容を表示 -->
          <li class="list-group-item study-log-list-tag">
            <div class="col-12">
              <div>学習内容</div>
            </div>
            <div class="col-12">
              <% study_log.tags.pluck(:name).each do |tag| %>
                <%= link_to tag,searchs_path(tag_name:tag,search_id:1,genre_id: 1),class: "badge-success p-1 badge-tag",data: {"turbolinks" => false} %>
              <% end %>
            </div>
          </li>
          <li class="list-group-item">
            <span class="col-3">
              学習時間
            </span>
            <span class="col-9">
              <%= study_log.hour %>時間<%=study_log.minute%>分
            </span>
          </li>
          <li class="list-group-item s-card-memo">
            <div class="card-body pt-2">
              <span class="absolute">
                学習メモ
              </span>
              <div class="mt-2 col-12">
                <%= study_log.memo %>
              </div>
            </div>
          </li>
        </ul>
        <div class="s-card-footer d-flex">
          <!-- いいね機能の処理 -->
          <span id="study-log-favorite-<%= study_log.id %>">
            <%= render 'study_log_favorites/study_log_favorite',study_log: study_log %>                
          </span>
          <span class="s-card-footer-margin">
            <%= link_to "詳細へ",study_log_path(study_log) %>
          </span>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/study_logs/edit.html.erb
<div class="container d-flex justify-content-center">
  <div class="study-log-new-width">  
    <div class="d-flex justify-content-start">
      <h3 class="mb-3">学習記録編集</h3>
      <%= link_to "戻る", study_log_path(@study_log), class: "study-log-back" %>
    </div>
    <div class="s-card">
      <%= form_with model: @study_log, local: true do |f| %> 
        <%= render 'layouts/error_messages', model: @study_log %>
        <div class="s-header">
          <h5>学習日</h5>
          <span>
            <%= f.date_field :working_date, value: Date.today, class: "form-control" %>
          </span>
        </div>
        <div class="d-flex card-body">
          <div class="content">
            <div class="row">      
              <span class="mt-2">
                学習内容
              </span>
              <span class="col-8">
                <%= f.text_field :tag_list,value: @study_log.tag_list.join(','),"data-role" => "tagsinput", class:"form-control"%>
              </span>
            </div>
            <hr>
            <div class="row">
              <div class="w-100  d-flex align-items-center ">
                <h6 class="mt-2">学習時間</h6>
                <div class="width ml-3 mr-1">
                  <%= f.select :hour, Array.new(24){|index| index },{},class: "form-control" %>
                </div>
                <h6 class="margin-right ml-1 mt-2">時間</h6>
                <div class="width">
                  <%= f.select :minute,Array.new(60){|index| index},{},class: "form-control" %>                
                </div>
                <h6 class="ml-2 mt-2">分</h6>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body pt-0">
          <%= f.label :memo,"メモ" %>
          <%= f.text_area :memo ,class: "form-control" %>
        </div>
      </div>
      <div class="mt-2 d-flex justify-content-end">
        <%= f.submit "登録する",class: "btn btn-primary"%>
        <%= link_to "削除する", study_log_path(@study_log),method: :delete, data: { confirm: "本当に削除しますか？",cancel: "やめる", commit: "削除する"},title: '投稿の削除',class: "ml-3 btn btn-danger"%>
      </div>
    <% end %>
  </div>
</div>

app/views/study_logs/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="study-log-new-width">
    <div class="d-flex justify-content-start">
      <h3 class="mb-3">学習記録編集</h3>
      <%= link_to "戻る", timelines_path, class: "study-log-back" %>
    </div>
    <div class="s-card">
      <%= form_with model: @study_log, local: true do |f| %> 
        <%= render 'layouts/error_messages', model: @study_log %>
        <div class="s-header">
          <h5>学習日</h5>
          <span>
            <%= f.date_field :working_date, value: Date.today, class: "form-control" %>
          </span>
        </div>
        <div class="d-flex card-body">
          <div class="content">
            <div class="row">
              <span class="mt-2">
                <%= f.label :tag_list,"学習内容" %>
              </span>
              <span class="col-8">
                <%= f.text_field :tag_list,value: @study_log.tag_list.join(','),"data-role" => "tagsinput",id: "add_study_log_tags", placeholder: "「,」区切りで追加してください",class:"form-control"%>
              </span>
            </div>
            <hr>
            <div class="row">
              <div class="w-100  d-flex align-items-center ">
                <h6 class="mt-2">学習時間</h6>
                <div class="width ml-3 mr-1">
                  <%= f.select :hour, Array.new(24){|index| index },{},class: "form-control" %>
                </div>
                <h6 class="margin-right ml-1 mt-2">時間</h6>
                <div class="width">
                  <%= f.select :minute,Array.new(60){|index| index},{},class: "form-control" %>
                </div>
                <h6 class="ml-2 mt-2">分</h6>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body pt-0">
          <%= f.label :memo %>
          <%= f.text_area :memo ,class: "form-control" %>
        </div>
        <div class="mt-2 d-flex justify-content-end">
          <%= f.submit "登録する",class: "btn btn-primary mr-3 mb-3", id:"study_log_input"%>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- render先で画面リロードを行うとroutingエラーが発生するため、明示的にパスを指定してリダイレクトさせる -->
<% if @study_log.errors.present? %>
<script type="text/javascript">
  $(document).ready(function() {
  history.pushState('', '', location.href + '/new')
  });
</script>
<% end %>

app/views/study_logs/show.html.erb
<div class="container study-log-show ">
  <div class="margin-auto width">
    <div class="d-flex justify-content-start">
      <h3 class="mb-3">学習記録編集</h3>
      <%= render 'study_logs/study_log_distribution', study_log: @study_log %>
    </div>
    <div class="s-card">
      <div class="study-log-show-parent">
        <div class="favorite-child">
          <!-- いいねの処理 -->
          <div id="study-log-favorite-<%= @study_log.id %>">
            <%= render 'study_log_favorites/study_log_favorite',study_log: @study_log %>
          </div>
        </div>
        <!-- 編集画面へのリンク -->
        <% if user_signed_in? && current_user.id == @study_log.user.id %>
          <span class="edit-link-child"><%= link_to "編集する",edit_study_log_path,data: {"turbolinks" => false} %></span>
        <% end %>
        <div class="s-header d-flex">
          <%= link_to user_path(@study_log.user.id) do %>
            <%= attachment_image_tag @study_log.user, :profile_image, :fill, 80, 80,  class: "pull-left profile-img", fallback: "no_image.png",size: "100x100" %>
          <% end %>
          <div class="ml-3 d-flex flex-column justify-content-center">
            <h6><%= @study_log.working_date.strftime("%Y年%m月%d日")%></h6>
            <h6><%= @study_log.user.name %></h6>
          </div>
        </div>
        <ul class="list-group">
          <!-- 登録された学習内容を表示 -->
          <li class="list-group-item study-log-show-study-tags" >
            <div class="col-12">
              <div>
                学習内容
              </div>
            </div>
            <div class="col-12">
              <% @study_log.tag_list.each do |tag| %>
                <%= link_to tag,searchs_path(tag_name:tag,search_id:1,genre_id: 1),class: "badge-success p-1 badge-tag",data: {"turbolinks" => false} %>
              <% end %>
            </div>
          </li>
          <li class="list-group-item">
            <span class="col-3">学習時間</span>
            <span class="col-9"><%= @study_log.hour %>時間<%= @study_log.minute %>分</span>
          </li>
          <li class="list-group-item s-card-memo">
            <div class="card-body pt-2">
              <span class="s-show-absolute">
                学習メモ
              </span>
              <div class="mt-2 col-12">
                <%= @study_log.memo %>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="width margin-auto">
    <h4 class="mt-4">コメント</h4>
    <div id="study-log-comments">
      <%= render 'study_log_comments/study_log_comments',study_log: @study_log, study_log_comments: @study_log_comments %>  
    </div>
    <%= render 'study_logs/study_log_form',study_log: @study_log ,study_log_comment: @study_log_comment %>
  </div>
</div>